name: cloud-collector  # 环境名称

channels:  # 包的来源渠道
  - conda-forge  # 社区维护的包，通常更新更快
  - defaults     # Anaconda 官方包

dependencies:  # 依赖列表
  - python=3.9  # 指定 Python 版本
  - pip  # 包管理器
  - pip:
    # Core web framework - most stable packages first
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - httpx==0.25.2
    - python-dotenv==1.0.0
    - pydantic==2.5.0 